REPORT zsap.
TABLES: d010sinf.

PARAMETERS: report(40) OBLIGATORY.
*DATA: ITAB(72) OCCURS 10 WITH HEADER LINE.
*DATA: ITAB(132) OCCURS 10 WITH HEADER LINE.
DATA: itab(255) OCCURS 10 WITH HEADER LINE.

START-OF-SELECTION.
  CHECK sy-uname = 'LMOURELATOS'.
  READ REPORT report INTO itab.
  CHECK sy-subrc = 0.
  EDITOR-CALL FOR itab.
  WRITE:/ sy-subrc.
  CHECK sy-subrc = 0.
  DELETE REPORT report STATE 'I'.
  INSERT REPORT report FROM itab.

END-OF-SELECTION.
